name: dipole
channels:
  - pytorch
  - open3d-admin
  - conda-forge
dependencies:
  - cudatoolkit=10.2
  - matplotlib
  - open3d=0.13.0
  - pip
  - pot=0.7.0
  - pytorch=1.9.0
  - requests
  - scikit-learn
  - tqdm
  - pip:
    - gudhi==3.4.0
    - umap-learn==0.5.1
